AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Student Grading System Lambda - V1

Resources:

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers: 
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt MyAuthFunction.Arn
  
  StudentLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.studentService
      Runtime: nodejs10.x
      CodeUri: ./LambdaCodeNodeJS
      #Policies:
      #  - DynamoDBCrudPolicy:
      #      TableName: !Ref carModelTableName
      #Environment:
      #  Variables:
      #    TABLE_NAME1: !Ref carModelTableName 
      Events:
        SearchModelAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /getStudentsList
            Method: get
      Timeout: 100

  MyAuthFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./authorizer
      Handler: handler.authorizer
      Runtime: nodejs10.x
