AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Student Grading System Lambda
Resources:
  StudentGradingLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: 'Lambda function for student grading system'
      MemorySize: 128
      Timeout: 30
      # Role: 'arn:aws:iam::397410853951:role/MyLambdaRole'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getzones
            Method: get
      Environment:
        Variables:
          REGION: ap-southeast-2
