AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Student Grading System Lambda - V1

Parameters:
  studentTableName:
    Type: String
    Default: car
    Description: Student table name
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: Required parameter. Must be characters only. No numbers allowed.
  studentMarksTableName:
      Type: String
      Default: carmodel
      Description: Student marks table name
      MinLength: 3
      MaxLength: 50
      AllowedPattern: ^[A-Za-z]+$
      ConstraintDescription: Required parameter. Must be characters only. No numbers allowed.
      
Resources:

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers: 
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt MyAuthFunction.Arn
 
  StudentSearchLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.studentService
      Runtime: nodejs14.x
      CodeUri: ./LambdaCodeNodeJS
      Description: 'Lambda JS function for student listing'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref studentMarksTableName
      Environment:
        Variables:
          TABLE_NAME1: !Ref studentMarksTableName 
      Events:
        SearchModelAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /getStudent/{studentId}
            Method: get
      Timeout: 100
      
  StudentGradingLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: student_lambda_function.student_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: 'Lambda function for student grading system with python'
      MemorySize: 128
      Timeout: 30
      Events:
        SearchModelAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /getstudents
            Method: get
      Environment:
        Variables:
          REGION: ap-southeast-1

  StudentDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref studentTableName
      AttributeDefinitions:
        - AttributeName: studentId
          AttributeType: S
      KeySchema:
        - AttributeName: studentId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  StudentMarksDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref studentMarksTableName
      AttributeDefinitions:
        - AttributeName: markId
          AttributeType: S
      KeySchema:
        - AttributeName: markId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      
  MyAuthFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./authorizer
      Handler: handler.authorizer
      Runtime: nodejs14.x
 
Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  ApiId:
    Description: "API ID"
    Value: !Ref MyApi

  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/'
